### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by mrk-its** [mrk-its/bevy-atari#18]
```
wasm.js:504 panicked at 'attempt to add with overflow', src/antic/mod.rs:244:9

Stack:

Error
    at imports.wbg.__wbg_new_693216e109162396 (https://mrk.sed.pl/bevy-atari/wasm/wasm.js:492:19)
```

**Comment by mrk-its** [comment]
or in Trix:
```
wasm.js:504 panicked at 'attempt to add with overflow', src/antic/mod.rs:354:13

Stack:
```
